language: minimal
addons:
  apt:
    packages:
      - docker-ce
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - PLATFORMS=linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
    - IMAGE=swarmpit/http-server
script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
  - docker buildx create --name multi
  - docker buildx use multi
  - docker buildx inspect --bootstrap
  - docker buildx build --platform $PLATFORMS -t $IMAGE --push .